// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using admintickets.Context;

#nullable disable

namespace admintickets.Migrations
{
    [DbContext(typeof(BestTicketContext))]
    partial class BestTicketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("admintickets.Models.DBModels.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Reduction")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("DiscountCode");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.SessionToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SessionToken");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Signal");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxNumberOfUsesPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.SubscriptionTiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("InternalDuration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaxNumberOfUsesPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("SubscriptionTier");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TicketPaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("TicketPaymentId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.TicketPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CodeUsedId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CodeUsedReduction")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PaymentAmountBeforeTax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PaymentAmountOfTax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PaymentAmountTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeUsedId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("TicketPayment");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("AccountDisableDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Code", b =>
                {
                    b.HasOne("admintickets.Models.DBModels.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.SessionToken", b =>
                {
                    b.HasOne("admintickets.Models.DBModels.User", "User")
                        .WithMany("SessionTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Signal", b =>
                {
                    b.HasOne("admintickets.Models.DBModels.Hospital", "Hospital")
                        .WithMany("Signals")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.SubscriptionTiers", b =>
                {
                    b.HasOne("admintickets.Models.DBModels.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Ticket", b =>
                {
                    b.HasOne("admintickets.Models.DBModels.Hospital", "Hospital")
                        .WithMany("Tickets")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("admintickets.Models.DBModels.TicketPayment", "TicketPayment")
                        .WithMany()
                        .HasForeignKey("TicketPaymentId");

                    b.Navigation("Hospital");

                    b.Navigation("TicketPayment");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.TicketPayment", b =>
                {
                    b.HasOne("admintickets.Models.DBModels.Code", "CodeUsed")
                        .WithMany("TicketPayments")
                        .HasForeignKey("CodeUsedId");

                    b.HasOne("admintickets.Models.DBModels.Subscription", "Subscription")
                        .WithMany("TicketPayments")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("CodeUsed");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Code", b =>
                {
                    b.Navigation("TicketPayments");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Hospital", b =>
                {
                    b.Navigation("Signals");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.Subscription", b =>
                {
                    b.Navigation("TicketPayments");
                });

            modelBuilder.Entity("admintickets.Models.DBModels.User", b =>
                {
                    b.Navigation("SessionTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
